sudo: required
services: -docker

before_install:
  - docker build  -t kpizzle/cypresstest .

script:
  # '-e ci=true' is env var so that tests exit and travis doesn't hang
  - docker run kpizzle/cypresstest

notifications:
  slack: kpdevhouse:LaFsABpD5hTZfZFnwUEUFTCf
